// src/lib/exportUtils.ts
import type { TaxCalculationResults } from '@/lib/taxCalculator';
import { formatCurrency } from '@/lib/utils';

export interface ExportData {
  results: TaxCalculationResults;
  salary: number;
  taxYear: string;
  taxCode: string;
  region: string;
  studentLoans: string[];
  exportDate: string;
}

export function generateCSV(data: ExportData): string {
  const { results, salary, taxYear, taxCode, region, studentLoans, exportDate } = data;
  
  const csvRows = [
    ['ToolHubX UK Tax Calculator Results'],
    ['Generated on', exportDate],
    [''],
    ['Input Details'],
    ['Gross Salary', formatCurrency(salary)],
    ['Tax Year', taxYear],
    ['Tax Code', taxCode || '1257L'],
    ['Region', region],
    ['Student Loans', studentLoans.join(', ') || 'None'],
    [''],
    ['Annual Breakdown'],
    ['Gross Salary', formatCurrency(results.grossSalary.annually)],
    ['Income Tax', `-${formatCurrency(results.incomeTax.annually)}`],
    ['National Insurance', `-${formatCurrency(results.nationalInsurance.annually)}`],
  ];

  // Add pension if applicable
  if (results.pensionContribution.annually > 0) {
    csvRows.push(['Pension Contribution', `-${formatCurrency(results.pensionContribution.annually)}`]);
  }

  // Add student loan if applicable
  if (results.studentLoan.annually > 0) {
    csvRows.push(['Student Loan Repayment', `-${formatCurrency(results.studentLoan.annually)}`]);
  }

  csvRows.push(
    ['Net Take-Home Pay', formatCurrency(results.netPay.annually)],
    [''],
    ['Monthly Breakdown'],
    ['Gross Salary', formatCurrency(results.grossSalary.monthly)],
    ['Income Tax', `-${formatCurrency(results.incomeTax.monthly)}`],
    ['National Insurance', `-${formatCurrency(results.nationalInsurance.monthly)}`]
  );

  // Add monthly pension if applicable
  if (results.pensionContribution.monthly > 0) {
    csvRows.push(['Pension Contribution', `-${formatCurrency(results.pensionContribution.monthly)}`]);
  }

  // Add monthly student loan if applicable
  if (results.studentLoan.monthly > 0) {
    csvRows.push(['Student Loan Repayment', `-${formatCurrency(results.studentLoan.monthly)}`]);
  }

  csvRows.push(
    ['Net Take-Home Pay', formatCurrency(results.netPay.monthly)],
    [''],
    ['Weekly Breakdown'],
    ['Gross Salary', formatCurrency(results.grossSalary.weekly)],
    ['Income Tax', `-${formatCurrency(results.incomeTax.weekly)}`],
    ['National Insurance', `-${formatCurrency(results.nationalInsurance.weekly)}`]
  );

  // Add weekly pension if applicable
  if (results.pensionContribution.weekly > 0) {
    csvRows.push(['Pension Contribution', `-${formatCurrency(results.pensionContribution.weekly)}`]);
  }

  // Add weekly student loan if applicable
  if (results.studentLoan.weekly > 0) {
    csvRows.push(['Student Loan Repayment', `-${formatCurrency(results.studentLoan.weekly)}`]);
  }

  csvRows.push(
    ['Net Take-Home Pay', formatCurrency(results.netPay.weekly)],
    [''],
    ['Tax Rates'],
    ['Effective Tax Rate', `${((results.incomeTax.annually + results.nationalInsurance.annually) / results.grossSalary.annually * 100).toFixed(1)}%`],
    ['Income Tax Rate', `${(results.incomeTax.annually / results.grossSalary.annually * 100).toFixed(1)}%`],
    ['National Insurance Rate', `${(results.nationalInsurance.annually / results.grossSalary.annually * 100).toFixed(1)}%`],
    [''],
    ['Generated by ToolHubX - https://toolhubx.uk']
  );

  return csvRows.map(row => row.join(',')).join('\n');
}

export function downloadCSV(csvContent: string, filename: string): void {
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
}

// PDF generation has been moved to @/lib/pdfExport.ts for better code splitting

function generatePrintHTML(data: ExportData): string {
  const { results, salary, taxYear, taxCode, region, studentLoans, exportDate } = data;
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>ToolHubX Tax Calculator Results</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #6366f1; padding-bottom: 20px; }
        .logo { font-size: 24px; font-weight: bold; color: #6366f1; margin-bottom: 10px; }
        .date { font-size: 14px; color: #666; }
        .section { margin: 30px 0; }
        .section h3 { color: #6366f1; border-bottom: 1px solid #e5e5e5; padding-bottom: 10px; }
        .details-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 20px 0; }
        .detail-item { display: flex; justify-content: space-between; padding: 8px 0; }
        .results-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .results-table th, .results-table td { padding: 12px; text-align: right; border-bottom: 1px solid #e5e5e5; }
        .results-table th { background: #f8f9fa; font-weight: 600; }
        .results-table td:first-child, .results-table th:first-child { text-align: left; }
        .total-row { background: #f0fdf4; font-weight: bold; }
        .negative { color: #dc2626; }
        .positive { color: #16a34a; }
        .footer { text-align: center; margin-top: 50px; font-size: 12px; color: #666; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo">ToolHubX</div>
        <h2>UK Tax Calculator Results</h2>
        <div class="date">Generated on ${exportDate}</div>
      </div>
      
      <div class="section">
        <h3>Input Details</h3>
        <div class="details-grid">
          <div class="detail-item"><span>Gross Salary:</span><span>${formatCurrency(salary)}</span></div>
          <div class="detail-item"><span>Tax Year:</span><span>${taxYear}</span></div>
          <div class="detail-item"><span>Tax Code:</span><span>${taxCode || '1257L'}</span></div>
          <div class="detail-item"><span>Region:</span><span>${region}</span></div>
          <div class="detail-item"><span>Student Loans:</span><span>${studentLoans.join(', ') || 'None'}</span></div>
        </div>
      </div>
      
      <div class="section">
        <h3>Tax Calculation Results</h3>
        <table class="results-table">
          <thead>
            <tr>
              <th>Description</th>
              <th>Annual</th>
              <th>Monthly</th>
              <th>Weekly</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Gross Salary</td>
              <td>${formatCurrency(results.grossSalary.annually)}</td>
              <td>${formatCurrency(results.grossSalary.monthly)}</td>
              <td>${formatCurrency(results.grossSalary.weekly)}</td>
            </tr>
            <tr>
              <td>Income Tax</td>
              <td class="negative">-${formatCurrency(results.incomeTax.annually)}</td>
              <td class="negative">-${formatCurrency(results.incomeTax.monthly)}</td>
              <td class="negative">-${formatCurrency(results.incomeTax.weekly)}</td>
            </tr>
            <tr>
              <td>National Insurance</td>
              <td class="negative">-${formatCurrency(results.nationalInsurance.annually)}</td>
              <td class="negative">-${formatCurrency(results.nationalInsurance.monthly)}</td>
              <td class="negative">-${formatCurrency(results.nationalInsurance.weekly)}</td>
            </tr>
            ${results.pensionContribution.annually > 0 ? `
            <tr>
              <td>Pension Contribution</td>
              <td class="negative">-${formatCurrency(results.pensionContribution.annually)}</td>
              <td class="negative">-${formatCurrency(results.pensionContribution.monthly)}</td>
              <td class="negative">-${formatCurrency(results.pensionContribution.weekly)}</td>
            </tr>` : ''}
            ${results.studentLoan.annually > 0 ? `
            <tr>
              <td>Student Loan Repayment</td>
              <td class="negative">-${formatCurrency(results.studentLoan.annually)}</td>
              <td class="negative">-${formatCurrency(results.studentLoan.monthly)}</td>
              <td class="negative">-${formatCurrency(results.studentLoan.weekly)}</td>
            </tr>` : ''}
            <tr class="total-row">
              <td><strong>Net Take-Home Pay</strong></td>
              <td class="positive"><strong>${formatCurrency(results.netPay.annually)}</strong></td>
              <td class="positive"><strong>${formatCurrency(results.netPay.monthly)}</strong></td>
              <td class="positive"><strong>${formatCurrency(results.netPay.weekly)}</strong></td>
            </tr>
          </tbody>
        </table>
      </div>
      
      <div class="section">
        <h3>Tax Rate Summary</h3>
        <div class="details-grid">
          <div class="detail-item"><span>Effective Tax Rate:</span><span>${((results.incomeTax.annually + results.nationalInsurance.annually) / results.grossSalary.annually * 100).toFixed(1)}%</span></div>
          <div class="detail-item"><span>Income Tax Rate:</span><span>${(results.incomeTax.annually / results.grossSalary.annually * 100).toFixed(1)}%</span></div>
          <div class="detail-item"><span>National Insurance Rate:</span><span>${(results.nationalInsurance.annually / results.grossSalary.annually * 100).toFixed(1)}%</span></div>
        </div>
      </div>
      
      <div class="footer">
        Generated by ToolHubX UK Tax Calculator<br>
        https://toolhubx.uk<br>
        Results calculated using official HMRC rates for ${taxYear}
      </div>
    </body>
    </html>
  `;
}