// src/lib/exportService.ts
/**
 * Export services for tax calculation results
 *
 * This module provides functionality to export tax calculation results
 * to different formats, including printable documents and CSV files.
 * It handles formatting and data preparation for export purposes.
 */

import type { DisplayPeriod } from '@/components/molecules/PeriodSelector';
import type { TaxCalculationResults } from '@/lib/taxCalculator';

/**
 * Generate a print-friendly window with tax calculation results
 *
 * Opens a new window with formatted tax calculation results
 * suitable for printing.
 *
 * @param results - Tax calculation results to print
 * @param selectedPeriods - Selected periods to include in the printout
 */
export function printResults(
  results: TaxCalculationResults,
  selectedPeriods: DisplayPeriod[]
): void {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    return;
  }

  // Create a formatted version of the results
  const formattedResults = formatResultsForPrint(results, selectedPeriods);

  printWindow.document.write(`
    <html>
      <head>
        <title>Tax Calculation Results - ToolHubX</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 
              'Open Sans', 'Helvetica Neue', sans-serif; 
            padding: 20px;
            color: #333;
            line-height: 1.5;
          }
          table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 20px;
            margin-bottom: 20px;
          }
          th, td { 
            padding: 10px 8px; 
            text-align: right; 
            border-bottom: 1px solid #ddd; 
          }
          th:first-child, td:first-child { 
            text-align: left; 
          }
          th { 
            background-color: #f2f2f2;
            font-weight: bold;
          }
          .title { 
            text-align: center; 
            margin-bottom: 20px; 
            font-size: 24px;
            color: #2563eb;
          }
          .subtitle {
            text-align: center;
            margin-bottom: 30px;
            font-size: 16px;
            color: #64748b;
          }
          .footer { 
            margin-top: 30px; 
            font-size: 12px; 
            text-align: center; 
            color: #64748b;
            border-top: 1px solid #ddd;
            padding-top: 10px;
          }
          .highlight {
            font-weight: bold;
            background-color: #f0f9ff;
          }
          .date {
            text-align: right;
            font-size: 12px;
            color: #64748b;
            margin-bottom: 30px;
          }
          .tax-notes {
            font-size: 12px;
            color: #64748b;
            margin-top: 20px;
            padding: 15px;
            border-left: 3px solid #2563eb;
            background-color: #f8fafc;
          }
          @media print {
            body { 
              font-size: 12pt; 
            }
            th, td {
              padding: 8px;
            }
            .tax-notes {
              page-break-inside: avoid;
            }
          }
        </style>
      </head>
      <body>
        <h1 class="title">Tax Calculation Results - ToolHubX</h1>
        <p class="subtitle">UK PAYE Tax Calculator for ${results.grossSalary.annually.toLocaleString('en-GB', { style: 'currency', currency: 'GBP' })} annual salary</p>
        <div class="date">Generated on ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
        ${formattedResults}
        <div class="tax-notes">
          <p><strong>Notes:</strong></p>
          <p>*Pension calculated as salary sacrifice; relief reflected in reduced tax and NI.</p>
          ${results.additionalAllowances?.annually ? '<p>**Additional allowances reduce your taxable income.</p>' : ''}
          <p>***This calculation is for illustrative purposes only and should not be used for tax filing.</p>
        </div>
        <div class="footer">
          Generated by ToolHubX UK PAYE Tax Calculator (toolhubx.uk)
          <br>
          This calculation is for illustrative purposes only. For official tax advice, consult HMRC or a qualified accountant.
        </div>
      </body>
    </html>
  `);

  printWindow.document.close();
  printWindow.print();
}

/**
 * Generate and download CSV file with tax calculation results
 *
 * Creates a CSV file with tax calculation results and triggers
 * a download in the browser.
 *
 * @param results - Tax calculation results to export
 * @param selectedPeriods - Selected periods to include in the CSV
 */
export function downloadCSV(
  results: TaxCalculationResults,
  selectedPeriods: DisplayPeriod[]
): void {
  let csvContent = 'Category,Percentage';

  // Add columns for each selected period
  for (const period of selectedPeriods) {
    const periodLabel = getPeriodLabel(period);
    csvContent += `,${periodLabel} (£)`;
  }
  csvContent += '\n';

  // Add rows for key metrics
  const metrics = [
    {
      name: 'Gross Pay',
      percentage: '100%',
      values: results.grossSalary,
      includeHourly: true,
    },
    {
      name: 'Personal Allowance',
      percentage: `${((results.taxFreeAmount / results.grossSalary.annually) * 100).toFixed(1)}%`,
      values: calculatePeriodValuesFromAnnual(results.taxFreeAmount, selectedPeriods, results),
      includeHourly: true,
    },
    {
      name: 'Total Taxable',
      percentage: `${((results.taxableIncome / results.grossSalary.annually) * 100).toFixed(1)}%`,
      values: calculatePeriodValuesFromAnnual(results.taxableIncome, selectedPeriods, results),
      includeHourly: true,
    },
    {
      name: 'Income Tax',
      percentage: `${((results.incomeTax.annually / results.grossSalary.annually) * 100).toFixed(1)}%`,
      values: results.incomeTax,
      includeHourly: false,
    },
    {
      name: 'National Insurance',
      percentage: `${((results.nationalInsurance.annually / results.grossSalary.annually) * 100).toFixed(1)}%`,
      values: results.nationalInsurance,
      includeHourly: false,
    },
  ];

  // Add optional rows based on what's in the results
  if (results.studentLoan.annually > 0) {
    metrics.push({
      name: 'Student Loan',
      percentage: `${((results.studentLoan.annually / results.grossSalary.annually) * 100).toFixed(1)}%`,
      values: results.studentLoan,
      includeHourly: false,
    });
  }

  if (results.pensionContribution.annually > 0) {
    metrics.push({
      name: 'Pension',
      percentage: `${((results.pensionContribution.annually / results.grossSalary.annually) * 100).toFixed(1)}%`,
      values: results.pensionContribution,
      includeHourly: false,
    });
  }

  // Always add net pay
  metrics.push({
    name: 'Net Pay',
    percentage: `${((results.netPay.annually / results.grossSalary.annually) * 100).toFixed(1)}%`,
    values: results.netPay,
    includeHourly: true,
  });

  // Add each row to the CSV content
  for (const metric of metrics) {
    csvContent += `${metric.name},${metric.percentage}`;

    for (const period of selectedPeriods) {
      // Special case for hourly values that don't apply
      if (period === 'hourly' && !metric.includeHourly) {
        csvContent += ',';
        continue;
      }

      const value = metric.values[period as keyof typeof metric.values];
      if (typeof value === 'number') {
        csvContent += `,${value.toFixed(2)}`;
      } else {
        csvContent += `,${value}`;
      }
    }

    csvContent += '\n';
  }

  // Create and download file
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', 'tax_calculation.csv');
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Get a human-readable label for a pay period
 *
 * @param period - The period to get a label for
 * @returns Human-readable period label
 */
function getPeriodLabel(period: DisplayPeriod): string {
  switch (period) {
    case 'annually':
      return 'Annual';
    case 'yearly':
      return 'Yearly';
    case 'monthly':
      return 'Monthly';
    case 'fourWeekly':
      return '4-Weekly';
    case 'fortnightly':
      return 'Fortnightly';
    case 'weekly':
      return 'Weekly';
    case 'daily':
      return 'Daily';
    case 'hourly':
      return 'Hourly';
    default:
      return period;
  }
}

/**
 * Helper function to calculate period values from annual amount
 *
 * @param annualValue - Annual value to convert
 * @param selectedPeriods - Periods to calculate for
 * @param results - Full calculation results (for hourly rate reference)
 * @returns Object with values for each period
 */
function calculatePeriodValuesFromAnnual(
  annualValue: number,
  selectedPeriods: DisplayPeriod[],
  results: TaxCalculationResults
): Record<string, number> {
  const values: Record<string, number> = {};

  for (const period of selectedPeriods) {
    switch (period) {
      case 'yearly':
        values[period] = annualValue;
        break;
      case 'monthly':
        values[period] = annualValue / 12;
        break;
      case 'fourWeekly':
        values[period] = annualValue / 13;
        break;
      case 'fortnightly':
        values[period] = annualValue / 26;
        break;
      case 'weekly':
        values[period] = annualValue / 52;
        break;
      case 'daily':
        values[period] = annualValue / 260;
        break;
      case 'hourly':
        values[period] =
          results.grossSalary.hourly > 0
            ? (annualValue / results.grossSalary.annually) * results.grossSalary.hourly
            : annualValue / (52 * 40); // Default to 40 hours/week if no hourly rate
        break;
    }
  }

  return values;
}

/**
 * Helper function to format results for print output
 *
 * @param results - Tax calculation results
 * @param selectedPeriods - Selected periods to include
 * @returns HTML string with formatted table
 */
function formatResultsForPrint(
  results: TaxCalculationResults,
  selectedPeriods: DisplayPeriod[]
): string {
  // Format period headers
  let tableHTML = '<table><thead><tr><th>Category</th><th>Percentage</th>';

  for (const period of selectedPeriods) {
    const periodLabel = getPeriodLabel(period);
    tableHTML += `<th>${periodLabel} (£)</th>`;
  }

  tableHTML += '</tr></thead><tbody>';

  // Format rows
  const formatter = new Intl.NumberFormat('en-GB', {
    style: 'currency',
    currency: 'GBP',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

  // Add Gross Pay row
  tableHTML += `<tr class="highlight">`;
  tableHTML += '<td>Gross Pay</td>';
  tableHTML += '<td>100%</td>';

  for (const period of selectedPeriods) {
    const value = results.grossSalary[period as keyof typeof results.grossSalary];
    tableHTML += `<td>${typeof value === 'number' ? formatter.format(value) : value}</td>`;
  }

  tableHTML += '</tr>';

  // Add Tax-Free Amount row
  const taxFreePercentage = ((results.taxFreeAmount / results.grossSalary.annually) * 100).toFixed(
    1
  );
  tableHTML += '<tr>';
  tableHTML += '<td>Personal Allowance</td>';
  tableHTML += `<td>${taxFreePercentage}%</td>`;

  for (const period of selectedPeriods) {
    const value = results.taxFreeAmount / getMultiplierForPeriod(period, results);
    tableHTML += `<td>${formatter.format(value)}</td>`;
  }

  tableHTML += '</tr>';

  // Add Taxable Income row
  const taxablePercentage = ((results.taxableIncome / results.grossSalary.annually) * 100).toFixed(
    1
  );
  tableHTML += '<tr>';
  tableHTML += '<td>Total Taxable</td>';
  tableHTML += `<td>${taxablePercentage}%</td>`;

  for (const period of selectedPeriods) {
    const value = results.taxableIncome / getMultiplierForPeriod(period, results);
    tableHTML += `<td>${formatter.format(value)}</td>`;
  }

  tableHTML += '</tr>';

  // Add Income Tax row
  const taxPercentage = ((results.incomeTax.annually / results.grossSalary.annually) * 100).toFixed(
    1
  );
  tableHTML += '<tr>';
  tableHTML += '<td>Income Tax</td>';
  tableHTML += `<td>${taxPercentage}%</td>`;

  for (const period of selectedPeriods) {
    const value = results.incomeTax[period as keyof typeof results.incomeTax];
    tableHTML += `<td>${typeof value === 'number' ? formatter.format(value) : value}</td>`;
  }

  tableHTML += '</tr>';

  // Add National Insurance row
  const niPercentage = (
    (results.nationalInsurance.annually / results.grossSalary.annually) *
    100
  ).toFixed(1);
  tableHTML += '<tr>';
  tableHTML += '<td>National Insurance</td>';
  tableHTML += `<td>${niPercentage}%</td>`;

  for (const period of selectedPeriods) {
    const value = results.nationalInsurance[period as keyof typeof results.nationalInsurance];
    tableHTML += `<td>${typeof value === 'number' ? formatter.format(value) : value}</td>`;
  }

  tableHTML += '</tr>';

  // Add Student Loan row if applicable
  if (results.studentLoan.annually > 0) {
    const slPercentage = (
      (results.studentLoan.annually / results.grossSalary.annually) *
      100
    ).toFixed(1);
    tableHTML += '<tr>';
    tableHTML += '<td>Student Loan</td>';
    tableHTML += `<td>${slPercentage}%</td>`;

    for (const period of selectedPeriods) {
      const value = results.studentLoan[period as keyof typeof results.studentLoan];
      tableHTML += `<td>${typeof value === 'number' ? formatter.format(value) : value}</td>`;
    }

    tableHTML += '</tr>';
  }

  // Add Pension row if applicable
  if (results.pensionContribution.annually > 0) {
    const pensionPercentage = (
      (results.pensionContribution.annually / results.grossSalary.annually) *
      100
    ).toFixed(1);
    tableHTML += '<tr>';
    tableHTML += '<td>Pension Contribution</td>';
    tableHTML += `<td>${pensionPercentage}%</td>`;

    for (const period of selectedPeriods) {
      const value = results.pensionContribution[period as keyof typeof results.pensionContribution];
      tableHTML += `<td>${typeof value === 'number' ? formatter.format(value) : value}</td>`;
    }

    tableHTML += '</tr>';
  }

  // Add Net Pay row (highlighted)
  const netPayPercentage = ((results.netPay.annually / results.grossSalary.annually) * 100).toFixed(
    1
  );
  tableHTML += `<tr class="highlight">`;
  tableHTML += '<td>Net Pay</td>';
  tableHTML += `<td>${netPayPercentage}%</td>`;

  for (const period of selectedPeriods) {
    const value = results.netPay[period as keyof typeof results.netPay];
    tableHTML += `<td>${typeof value === 'number' ? formatter.format(value) : value}</td>`;
  }

  tableHTML += '</tr>';

  tableHTML += '</tbody></table>';

  return tableHTML;
}

/**
 * Helper function to get period multiplier
 *
 * @param period - The period to get a multiplier for
 * @param results - Full calculation results (for hourly rate reference)
 * @returns Divisor to convert annual amount to period amount
 */
function getMultiplierForPeriod(period: DisplayPeriod, results: TaxCalculationResults): number {
  switch (period) {
    case 'yearly':
      return 1;
    case 'monthly':
      return 12;
    case 'fourWeekly':
      return 13;
    case 'fortnightly':
      return 26;
    case 'weekly':
      return 52;
    case 'daily':
      return 260;
    case 'hourly':
      return results.grossSalary.hourly > 0
        ? results.grossSalary.annually / results.grossSalary.hourly
        : 52 * 40; // Default to 40 hours/week if no hourly rate
  }
}
