// src/lib/__tests__/__mocks__/contentlayer.mock.ts
module.exports = {
  allPosts: [
    {
      _id: '1',
      title: 'Test Post 1',
      slugAsParams: 'test-post-1',
      excerpt: 'This is test post 1',
      publishedAt: '2024-01-01',
      category: 'tax-basics',
      body: { raw: 'Content 1', code: '' },
      published: true,
      featured: true,
      author: 'Test Author',
      readingTime: 5,
      keywords: ['tax', 'basics'],
      image: '/images/test1.jpg',
      imageAlt: 'Test Image 1',
    },
    {
      _id: '2',
      title: 'Test Post 2',
      slugAsParams: 'test-post-2',
      excerpt: 'This is test post 2',
      publishedAt: '2024-01-15',
      category: 'tax-tips',
      body: { raw: 'Content 2', code: '' },
      published: true,
      featured: false,
      author: 'Test Author 2',
      readingTime: 3,
      keywords: ['tax', 'tips'],
    },
    {
      _id: '3',
      title: 'Draft Post',
      slugAsParams: 'draft-post',
      excerpt: 'This is a draft',
      publishedAt: '2024-02-01',
      category: 'tax-basics',
      body: { raw: 'Draft content', code: '' },
      published: false,
      featured: false,
      author: 'Test Author',
      readingTime: 4,
    },
    {
      _id: '4',
      title: 'Another Tax Basics Post',
      slugAsParams: 'another-tax-basics',
      excerpt: 'More tax basics',
      publishedAt: '2023-12-01',
      category: 'tax-basics',
      body: { raw: 'More content', code: '' },
      published: true,
      featured: false,
      author: 'Test Author',
      readingTime: 6,
      keywords: ['tax', 'basics', 'advanced'],
    },
  ],
};
