version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      tooling:
        patterns:
          - "@biomejs/*"
          - "typescript"
          - "@types/*"
          - "knip"
          - "jest"
          - "@playwright/*"
        update-types:
          - "minor"
          - "patch"
      nextjs-and-react:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@next/*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
