/**
 * Independent HMRC tax-code interpretation fixtures.
 *
 * Expectations here are transcribed from the official sources below. They are
 * deliberately kept outside the decoder implementation so tests do not use
 * production output as their own oracle.
 */

export const HMRC_TAX_CODE_FIXTURE_SOURCES = {
  verifiedOn: '2026-08-23',
  urls: [
    'https://www.gov.uk/tax-codes/what-your-tax-code-means',
    'https://www.gov.uk/employee-tax-codes/letters',
    'https://www.gov.uk/tax-codes/k-in-your-tax-code',
    'https://www.gov.uk/tax-codes/emergency-tax-codes',
    'https://www.gov.uk/hmrc-internal-manuals/paye-manual/paye11015',
    'https://www.gov.uk/hmrc-internal-manuals/paye-manual/paye11050',
    'https://www.gov.uk/hmrc-internal-manuals/paye-manual/paye11090',
  ],
} as const;

export interface TaxCodeVerificationFixture {
  code: string;
  classification: 'standard' | 'k-code' | 'flat-rate' | 'zero-allowance' | 'no-tax';
  prefix: 'S' | 'C' | null;
  letter: string;
  allowance: number;
  kAdjustment: number;
  marker: 'W1' | 'M1' | 'X' | 'NONCUM' | null;
  meaningIncludes: string;
  detailIncludes: string;
  amountLabel: string | null;
  amount: number | null;
}

export const VALID_TAX_CODE_FIXTURES: readonly TaxCodeVerificationFixture[] = [
  {
    code: '1257L',
    classification: 'standard',
    prefix: null,
    letter: 'L',
    allowance: 12_570,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Standard Personal Allowance',
    detailIncludes: 'tax-free income from this employment or pension',
    amountLabel: 'Tax-free amount from this source',
    amount: 12_570,
  },
  {
    code: 'S1257L',
    classification: 'standard',
    prefix: 'S',
    letter: 'L',
    allowance: 12_570,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Standard Personal Allowance',
    detailIncludes: 'Scottish Income Tax rates',
    amountLabel: 'Tax-free amount from this source',
    amount: 12_570,
  },
  {
    code: 'C1257L',
    classification: 'standard',
    prefix: 'C',
    letter: 'L',
    allowance: 12_570,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Standard Personal Allowance',
    detailIncludes: 'Welsh Income Tax rates',
    amountLabel: 'Tax-free amount from this source',
    amount: 12_570,
  },
  {
    code: '1383M',
    classification: 'standard',
    prefix: null,
    letter: 'M',
    allowance: 13_830,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Marriage Allowance received',
    detailIncludes: 'already reflects HMRC',
    amountLabel: 'Tax-free amount from this source',
    amount: 13_830,
  },
  {
    code: '1131N',
    classification: 'standard',
    prefix: null,
    letter: 'N',
    allowance: 11_310,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Marriage Allowance transferred',
    detailIncludes: 'already reflects HMRC',
    amountLabel: 'Tax-free amount from this source',
    amount: 11_310,
  },
  {
    code: '1000T',
    classification: 'standard',
    prefix: null,
    letter: 'T',
    allowance: 10_000,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'HMRC needs to review some items',
    detailIncludes: 'tax-free income from this employment or pension',
    amountLabel: 'Tax-free amount from this source',
    amount: 10_000,
  },
  {
    code: '0T',
    classification: 'zero-allowance',
    prefix: null,
    letter: '0T',
    allowance: 0,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'No tax-free amount through this code',
    detailIncludes: 'Personal Allowance has been used up',
    amountLabel: 'Tax-free amount from this source',
    amount: 0,
  },
  {
    code: 'K475',
    classification: 'k-code',
    prefix: null,
    letter: 'K',
    allowance: -4_750,
    kAdjustment: 4_750,
    marker: null,
    meaningIncludes: 'Amount added to taxable pay',
    detailIncludes: '£4,750 is added to taxable pay',
    amountLabel: 'Added to taxable pay',
    amount: 4_750,
  },
  {
    code: 'SD0',
    classification: 'flat-rate',
    prefix: 'S',
    letter: 'D0',
    allowance: 0,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Scottish intermediate rate',
    detailIncludes: '21%',
    amountLabel: null,
    amount: null,
  },
  {
    code: 'SD1',
    classification: 'flat-rate',
    prefix: 'S',
    letter: 'D1',
    allowance: 0,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Scottish higher rate',
    detailIncludes: '42%',
    amountLabel: null,
    amount: null,
  },
  {
    code: 'SD2',
    classification: 'flat-rate',
    prefix: 'S',
    letter: 'D2',
    allowance: 0,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Scottish advanced rate',
    detailIncludes: '45%',
    amountLabel: null,
    amount: null,
  },
  {
    code: 'SD3',
    classification: 'flat-rate',
    prefix: 'S',
    letter: 'D3',
    allowance: 0,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Scottish top rate',
    detailIncludes: '48%',
    amountLabel: null,
    amount: null,
  },
  {
    code: 'CD0',
    classification: 'flat-rate',
    prefix: 'C',
    letter: 'D0',
    allowance: 0,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Welsh higher rate',
    detailIncludes: '40%',
    amountLabel: null,
    amount: null,
  },
  {
    code: 'CD1',
    classification: 'flat-rate',
    prefix: 'C',
    letter: 'D1',
    allowance: 0,
    kAdjustment: 0,
    marker: null,
    meaningIncludes: 'Welsh additional rate',
    detailIncludes: '45%',
    amountLabel: null,
    amount: null,
  },
  {
    code: '1257L W1',
    classification: 'standard',
    prefix: null,
    letter: 'L',
    allowance: 12_570,
    kAdjustment: 0,
    marker: 'W1',
    meaningIncludes: 'Standard Personal Allowance',
    detailIncludes: 'weekly pay',
    amountLabel: 'Tax-free amount from this source',
    amount: 12_570,
  },
  {
    code: 'S875L M1',
    classification: 'standard',
    prefix: 'S',
    letter: 'L',
    allowance: 8_750,
    kAdjustment: 0,
    marker: 'M1',
    meaningIncludes: 'Standard Personal Allowance',
    detailIncludes: 'monthly pay',
    amountLabel: 'Tax-free amount from this source',
    amount: 8_750,
  },
  {
    code: 'C663L X',
    classification: 'standard',
    prefix: 'C',
    letter: 'L',
    allowance: 6_630,
    kAdjustment: 0,
    marker: 'X',
    meaningIncludes: 'Standard Personal Allowance',
    detailIncludes: 'pay dates vary',
    amountLabel: 'Tax-free amount from this source',
    amount: 6_630,
  },
  {
    code: '1257L NONCUM',
    classification: 'standard',
    prefix: null,
    letter: 'L',
    allowance: 12_570,
    kAdjustment: 0,
    marker: 'NONCUM',
    meaningIncludes: 'Standard Personal Allowance',
    detailIncludes: 'payroll software',
    amountLabel: 'Tax-free amount from this source',
    amount: 12_570,
  },
  {
    code: 'K475 W1',
    classification: 'k-code',
    prefix: null,
    letter: 'K',
    allowance: -4_750,
    kAdjustment: 4_750,
    marker: 'W1',
    meaningIncludes: 'Amount added to taxable pay',
    detailIncludes: 'weekly pay',
    amountLabel: 'Added to taxable pay',
    amount: 4_750,
  },
  {
    code: 'BR M1',
    classification: 'flat-rate',
    prefix: null,
    letter: 'BR',
    allowance: 0,
    kAdjustment: 0,
    marker: 'M1',
    meaningIncludes: 'Basic rate',
    detailIncludes: 'monthly pay',
    amountLabel: null,
    amount: null,
  },
  {
    code: 'SD0 X',
    classification: 'flat-rate',
    prefix: 'S',
    letter: 'D0',
    allowance: 0,
    kAdjustment: 0,
    marker: 'X',
    meaningIncludes: 'Scottish intermediate rate',
    detailIncludes: 'pay dates vary',
    amountLabel: null,
    amount: null,
  },
  {
    code: 'NT NONCUM',
    classification: 'no-tax',
    prefix: null,
    letter: 'NT',
    allowance: 0,
    kAdjustment: 0,
    marker: 'NONCUM',
    meaningIncludes: 'No tax deducted',
    detailIncludes: 'payroll software',
    amountLabel: null,
    amount: null,
  },
];

export const INVALID_TAX_CODE_FIXTURES = [
  '1257',
  'K0',
  'K10000',
  'D2',
  'D3',
  'CD2',
  'CD3',
  'SD4',
  'SD8',
  'SNT',
  'CNT',
  '1257P',
  '1257L W',
  '1257L M',
  '1257L W1 M1',
  'NONCUM',
  '0L',
  '100000L',
  '9999999999999999L',
] as const;
