/**
 * Existing hardcoded tax-fact findings outside approved/excepted locations.
 *
 * Counts are stable across line movement. Reduce or remove entries when debt is
 * eliminated; do not increase them to make an unexpected finding disappear.
 */
const BASELINE_ENTRIES = [
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '1000', 2],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '1260', 2],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '5000', 4],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '12570', 10],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '21000', 1],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '25000', 1],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '26065', 1],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '28470', 3],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '32745', 1],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '50270', 2],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '100000', 1],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'policy-value', '125140', 3],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'rate', '0', 1],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'rate', '8', 1],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'rate', '12', 1],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'rate', '20', 6],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'rate', '40', 4],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'rate', '45', 1],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'rate', '50', 1],
  ['content/blog/beginners-guide-to-uk-taxation.mdx', 'tax-year', '2025-2026', 5],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'policy-value', '12570', 1],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'policy-value', '50000', 1],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'policy-value', '50270', 1],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'rate', '2', 3],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'rate', '5', 1],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'rate', '8', 3],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'rate', '9', 1],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'rate', '15', 1],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'rate', '20', 4],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'rate', '40', 4],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'rate', '42', 1],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'rate', '50', 1],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'tax-year', '2025-2026', 5],
  ['content/blog/electric-car-salary-sacrifice-guide.mdx', 'tax-year', '2026-2027', 22],
  ['content/blog/understanding-uk-tax-codes.mdx', 'policy-value', '500', 2],
  ['content/blog/understanding-uk-tax-codes.mdx', 'policy-value', '1260', 1],
  ['content/blog/understanding-uk-tax-codes.mdx', 'policy-value', '12570', 5],
  ['content/blog/understanding-uk-tax-codes.mdx', 'policy-value', '125140', 1],
  ['content/blog/understanding-uk-tax-codes.mdx', 'rate', '20', 5],
  ['content/blog/understanding-uk-tax-codes.mdx', 'rate', '40', 4],
  ['content/blog/understanding-uk-tax-codes.mdx', 'rate', '45', 3],
  ['content/blog/understanding-uk-tax-codes.mdx', 'tax-year', '2025-2026', 3],
  ['e2e/scripts/generate-golden-master.ts', 'policy-value', '12570', 1],
  ['e2e/scripts/generate-golden-master.ts', 'policy-value', '26065', 1],
  ['e2e/scripts/generate-golden-master.ts', 'policy-value', '50270', 1],
  ['e2e/scripts/generate-golden-master.ts', 'rate', '20', 1],
  ['e2e/scripts/generate-golden-master.ts', 'rate', '40', 1],
  ['e2e/scripts/generate-golden-master.ts', 'rate', '45', 1],
  ['e2e/scripts/generate-golden-master.ts', 'rate', '48', 1],
  ['e2e/scripts/generate-golden-master.ts', 'tax-year', '2025-2026', 5],
  ['e2e/scripts/generate-golden-master.ts', 'tax-year', '2026-2027', 3],
  ['scripts/audit-blog-content.ts', 'tax-year', '2025-2026', 1],
  ['scripts/audit-blog-content.ts', 'tax-year', '2026-2027', 1],
  [
    'src/app/tools/marriage-allowance-calculator/MarriageAllowanceClient.tsx',
    'policy-value',
    '12570',
    1,
  ],
  ['src/app/tools/marriage-allowance-calculator/MarriageAllowanceClient.tsx', 'rate', '20', 2],
  ['src/app/tools/national-insurance-calculator/NICalculatorClient.tsx', 'policy-value', '5000', 1],
  ['src/app/tools/national-insurance-calculator/NICalculatorClient.tsx', 'policy-value', '9100', 1],
  ['src/app/tools/national-insurance-calculator/NICalculatorClient.tsx', 'rate', '13.8', 1],
  ['src/app/tools/national-insurance-calculator/NICalculatorClient.tsx', 'rate', '15', 1],
  [
    'src/app/tools/scottish-tax-calculator/ScottishTaxCalculatorClient.tsx',
    'policy-value',
    '12570',
    1,
  ],
  [
    'src/app/tools/scottish-tax-calculator/ScottishTaxCalculatorClient.tsx',
    'policy-value',
    '50270',
    1,
  ],
  [
    'src/app/tools/scottish-tax-calculator/ScottishTaxCalculatorClient.tsx',
    'policy-value',
    '125140',
    3,
  ],
  ['src/app/tools/scottish-tax-calculator/ScottishTaxCalculatorClient.tsx', 'rate', '19', 1],
  ['src/app/tools/scottish-tax-calculator/ScottishTaxCalculatorClient.tsx', 'rate', '20', 1],
  ['src/app/tools/scottish-tax-calculator/ScottishTaxCalculatorClient.tsx', 'rate', '21', 1],
  ['src/app/tools/scottish-tax-calculator/ScottishTaxCalculatorClient.tsx', 'rate', '40', 2],
  ['src/app/tools/scottish-tax-calculator/ScottishTaxCalculatorClient.tsx', 'rate', '42', 2],
  ['src/app/tools/scottish-tax-calculator/ScottishTaxCalculatorClient.tsx', 'rate', '45', 3],
  ['src/app/tools/scottish-tax-calculator/ScottishTaxCalculatorClient.tsx', 'rate', '48', 2],
  ['src/app/tools/tax-code-decoder/TaxCodeDecoderClient.tsx', 'rate', '20', 1],
  ['src/app/tools/tax-code-decoder/TaxCodeDecoderClient.tsx', 'rate', '40', 1],
  ['src/app/tools/tax-code-decoder/TaxCodeDecoderClient.tsx', 'rate', '45', 1],
  [
    'src/components/molecules/DirectorGuide/calculator/PensionGapWarning.tsx',
    'policy-value',
    '5000',
    2,
  ],
  [
    'src/components/molecules/DirectorGuide/calculator/PensionGapWarning.tsx',
    'policy-value',
    '6500',
    2,
  ],
  ['src/components/molecules/DirectorGuide/calculator/PensionGapWarning.tsx', 'rate', '12', 1],
  ['src/components/molecules/DirectorGuide/calculator/PensionGapWarning.tsx', 'rate', '15', 1],
  [
    'src/components/molecules/DirectorGuide/dashboard/EducationPanel.tsx',
    'policy-value',
    '1000',
    6,
  ],
  [
    'src/components/molecules/DirectorGuide/dashboard/EducationPanel.tsx',
    'policy-value',
    '50000',
    1,
  ],
  ['src/components/molecules/DirectorGuide/dashboard/EducationPanel.tsx', 'rate', '19', 1],
  ['src/components/molecules/DirectorGuide/dashboard/EducationPanel.tsx', 'rate', '25', 1],
  ['src/components/molecules/DirectorGuide/dashboard/EducationPanel.tsx', 'rate', '33.75', 1],
  [
    'src/components/molecules/DirectorGuide/dashboard/SurvivalModePanel.tsx',
    'policy-value',
    '6500',
    1,
  ],
  [
    'src/components/molecules/DirectorGuide/dashboard/SurvivalModePanel.tsx',
    'tax-year',
    '2025-2026',
    1,
  ],
  [
    'src/components/molecules/DirectorGuide/inputs/EmploymentAllowanceInput.tsx',
    'policy-value',
    '10500',
    1,
  ],
  ['src/components/molecules/DirectorGuide/inputs/PensionInput.tsx', 'policy-value', '60000', 1],
  ['src/components/molecules/MarriageAllowanceAlert.tsx', 'policy-value', '12570', 3],
  ['src/components/molecules/MarriageAllowanceAlert.tsx', 'policy-value', '50270', 1],
  ['src/components/molecules/TaxTrapInlineAlert.tsx', 'policy-value', '12570', 1],
  ['src/components/molecules/TaxTrapInlineAlert.tsx', 'policy-value', '100000', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'policy-value', '500', 2],
  ['src/components/organisms/CalculatorContent.tsx', 'policy-value', '1000', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'policy-value', '1260', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'policy-value', '3130', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'policy-value', '12570', 5],
  ['src/components/organisms/CalculatorContent.tsx', 'policy-value', '50000', 3],
  ['src/components/organisms/CalculatorContent.tsx', 'policy-value', '50270', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'policy-value', '100000', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'policy-value', '125140', 2],
  ['src/components/organisms/CalculatorContent.tsx', 'rate', '0', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'rate', '8', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'rate', '19', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'rate', '20', 6],
  ['src/components/organisms/CalculatorContent.tsx', 'rate', '21', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'rate', '40', 3],
  ['src/components/organisms/CalculatorContent.tsx', 'rate', '42', 1],
  ['src/components/organisms/CalculatorContent.tsx', 'rate', '45', 3],
  ['src/components/organisms/CalculatorContent.tsx', 'rate', '48', 2],
  ['src/components/organisms/CalculatorContent.tsx', 'tax-year', '2025-2026', 4],
  ['src/components/organisms/CalculatorInputs/BasicInputs.tsx', 'tax-year', '2023-2024', 1],
  ['src/components/organisms/CalculatorResults/ResultsTable.tsx', 'tax-year', '2025-2026', 1],
  ['src/lib/blog.ts', 'tax-year', '2025-2026', 2],
  ['src/lib/crawlableTaxFacts.ts', 'policy-value', '125140', 1],
  ['src/lib/crawlableTaxFacts.ts', 'rate', '0', 3],
  ['src/lib/email/directorResultsEmail.ts', 'tax-year', '2026-2027', 2],
  ['src/lib/email/payeResultsEmail.ts', 'tax-year', '2025-2026', 2],
  ['src/lib/pensionOptimizer.ts', 'policy-value', '5000', 1],
  ['src/lib/pensionOptimizer.ts', 'policy-value', '12570', 1],
  ['src/lib/pensionOptimizer.ts', 'policy-value', '100000', 1],
  ['src/lib/pensionOptimizer.ts', 'policy-value', '125140', 1],
  ['src/lib/pensionOptimizer.ts', 'rate', '20', 2],
  ['src/lib/pensionOptimizer.ts', 'rate', '25', 2],
  ['src/lib/pensionOptimizer.ts', 'rate', '40', 2],
  ['src/lib/pensionOptimizer.ts', 'tax-year', '2025-2026', 2],
  ['src/lib/sentry.ts', 'tax-year', '2025-2026', 4],
  ['src/lib/taxCalculator.ts', 'policy-value', '1000', 2],
  ['src/lib/taxCalculator.ts', 'policy-value', '1260', 1],
  ['src/lib/taxCalculator.ts', 'policy-value', '12570', 3],
  ['src/lib/taxCalculator.ts', 'policy-value', '37700', 2],
  ['src/lib/taxCalculator.ts', 'policy-value', '50000', 1],
  ['src/lib/taxCalculator.ts', 'policy-value', '50270', 1],
  ['src/lib/taxCalculator.ts', 'policy-value', '100000', 2],
  ['src/lib/taxCalculator.ts', 'policy-value', '125140', 2],
  ['src/lib/taxCalculator.ts', 'rate', '0', 2],
  ['src/lib/taxCalculator.ts', 'rate', '2', 1],
  ['src/lib/taxCalculator.ts', 'rate', '8', 1],
  ['src/lib/taxCalculator.ts', 'rate', '20', 7],
  ['src/lib/taxCalculator.ts', 'rate', '21', 1],
  ['src/lib/taxCalculator.ts', 'rate', '40', 7],
  ['src/lib/taxCalculator.ts', 'rate', '42', 2],
  ['src/lib/taxCalculator.ts', 'rate', '45', 4],
  ['src/lib/taxCalculator.ts', 'rate', '48', 1],
  ['src/lib/taxCalculator.ts', 'tax-year', '2023-2024', 2],
  ['src/lib/taxCalculator.ts', 'tax-year', '2024-2025', 6],
  ['src/lib/taxCalculator.ts', 'tax-year', '2025-2026', 1],
  ['src/lib/validation.ts', 'tax-year', '2024-2025', 5],
  ['src/lib/validation.ts', 'tax-year', '2025-2026', 1],
  ['src/lib/validation/directorValidation.ts', 'policy-value', '12570', 1],
  ['src/lib/validation/directorValidation.ts', 'policy-value', '50000', 1],
  ['src/lib/validation/directorValidation.ts', 'policy-value', '60000', 1],
  ['src/lib/validation/directorValidation.ts', 'rate', '20', 1],
  ['src/lib/validation/emailValidation.ts', 'tax-year', '2024-2025', 2],
  ['src/lib/validation/emailValidation.ts', 'tax-year', '2025-2026', 2],
  ['src/lib/validation/uiValidation.ts', 'tax-year', '2024-2025', 4],
  ['src/lib/validation/uiValidation.ts', 'tax-year', '2025-2026', 2],
  ['src/store/calculatorStore.ts', 'tax-year', '2024-2025', 3],
] as const;

export const TAX_FACT_BASELINE = BASELINE_ENTRIES.map(([file, kind, value, count]) => ({
  file,
  kind,
  value,
  count,
}));
