// src/components/organisms/ResultsTableExport.ts
// Export functions for printing and generating CSV from tax calculation results

import { getPeriodValues } from '@/lib/periodCalculator';
import type { TaxCalculationResults } from '@/lib/taxCalculator';
import type { DisplayPeriod } from '../molecules/PeriodSelector';

/**
 * Generate a print-friendly window with table contents
 * @param printContent HTML content to print
 */
export const generatePrintContent = (printContent: string): void => {
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(`
      <html>
        <head>
          <title>Tax Calculation Results - ToolHubX</title>
          <style>
            body { font-family: Arial, sans-serif; }
            table { width: 100%; border-collapse: collapse; }
            th, td { padding: 8px; text-align: right; border-bottom: 1px solid #ddd; }
            th:first-child, td:first-child { text-align: left; }
            th { background-color: #f2f2f2; }
            .title { text-align: center; margin-bottom: 20px; }
            .footer { margin-top: 20px; font-size: 12px; text-align: center; color: #666; }
          </style>
        </head>
        <body>
          <h1 class="title">Tax Calculation Results - ToolHubX</h1>
          ${printContent}
          <div class="footer">
            Generated by ToolHubX UK PAYE Tax Calculator (toolhubx.uk)
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  }
};

/**
 * Generate CSV content from tax calculation results
 * @param results Tax calculation results
 * @param selectedPeriods Selected periods to include in the CSV
 */
export const generateCSVContent = (
  results: TaxCalculationResults,
  selectedPeriods: DisplayPeriod[]
): void => {
  let csvContent = 'Category,Percentage';

  // Add columns for each selected period
  for (const period of selectedPeriods) {
    const periodLabel =
      period === 'yearly'
        ? 'Yearly'
        : period === 'monthly'
          ? 'Monthly'
          : period === 'fourWeekly'
            ? '4-Weekly'
            : period === 'fortnightly'
              ? 'Fortnightly'
              : period === 'weekly'
                ? 'Weekly'
                : period === 'daily'
                  ? 'Daily'
                  : 'Hourly';
    csvContent += `,${periodLabel} (£)`;
  }
  csvContent += '\n';

  // Add rows for each category
  const categories = [
    {
      name: 'Gross Pay',
      percentage: '100%',
      annual: results.grossSalary.annually,
      includeHourly: true,
    },
    {
      name: 'Tax-Free Allowance',
      percentage: `${((results.taxFreeAmount / results.grossSalary.annually) * 100).toFixed(1)}%`,
      annual: results.taxFreeAmount,
      includeHourly: true,
    },
    {
      name: 'Total Taxable',
      percentage: `${((results.taxableIncome / results.grossSalary.annually) * 100).toFixed(1)}%`,
      annual: results.taxableIncome,
      includeHourly: true,
    },
    {
      name: 'Total Tax Due',
      percentage: `${((results.incomeTax.annually / results.grossSalary.annually) * 100).toFixed(1)}%`,
      annual: results.incomeTax.annually,
      includeHourly: false,
    },
    {
      name: 'National Insurance',
      percentage: `${((results.nationalInsurance.annually / results.grossSalary.annually) * 100).toFixed(1)}%`,
      annual: results.nationalInsurance.annually,
      includeHourly: false,
    },
    {
      name: 'Pension [You]',
      percentage: `${((results.pensionContribution.annually / results.grossSalary.annually) * 100).toFixed(1)}%`,
      annual: results.pensionContribution.annually,
      includeHourly: false,
    },
    {
      name: 'Net Pay',
      percentage: `${((results.netPay.annually / results.grossSalary.annually) * 100).toFixed(1)}%`,
      annual: results.netPay.annually,
      includeHourly: true,
    },
  ];

  // Add each category to the CSV
  for (const category of categories) {
    csvContent += `${category.name},${category.percentage}`;

    // Calculate period values for this category
    const periodValues = getPeriodValues(category.annual, selectedPeriods);

    for (const period of selectedPeriods) {
      // Skip hourly values for categories that don't have them
      if (period === 'hourly' && !category.includeHourly) {
        csvContent += ',';
        continue;
      }

      // Safely access the value for this period
      const value = periodValues[period];
      csvContent += `,${value.toFixed(2)}`;
    }

    csvContent += '\n';
  }

  // Create and download the file
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');

  link.setAttribute('href', url);
  link.setAttribute('download', 'tax_calculation.csv');
  link.style.visibility = 'hidden';

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
