// src/components/organisms/TableOfContents.tsx
'use client';

import GithubSlugger from 'github-slugger';
import { List } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { ICON_SIZES, TYPOGRAPHY } from '@/constants/designTokens';
import { cn } from '@/lib/utils';

interface TocItem {
  id: string;
  text: string;
  index: number;
}

interface TableOfContentsProps {
  content: string;
  className?: string;
}

/**
 * Extract h2 headings from markdown content.
 * Uses github-slugger to match the IDs generated by rehype-slug and mdx-components.
 * Handles duplicate headings by appending -1, -2, etc. (github-slugger behavior).
 */
function extractHeadings(content: string): TocItem[] {
  // Create a new slugger for each extraction to reset duplicate tracking
  const slugger = new GithubSlugger();
  const headingRegex = /^##\s+(.+)$/gm;
  const headings: TocItem[] = [];
  let index = 0;

  for (const match of content.matchAll(headingRegex)) {
    const text = match[1]?.trim();
    if (!text) continue;

    // Use github-slugger to generate IDs that match rehype-slug
    const id = slugger.slug(text);
    headings.push({ id, text, index });
    index++;
  }

  return headings;
}

export function TableOfContents({ content, className }: TableOfContentsProps) {
  const [activeId, setActiveId] = useState<string>('');

  // Memoize headings to prevent effect churn on every render
  const headings = useMemo(() => extractHeadings(content), [content]);

  useEffect(() => {
    if (headings.length === 0) return;

    const observer = new IntersectionObserver(
      (entries) => {
        // Filter to only intersecting entries
        const visible = entries.filter((e) => e.isIntersecting);
        if (visible.length === 0) return;

        // Sort by position from top of viewport - choose the one nearest the top
        visible.sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
        const topEntry = visible[0];
        if (topEntry) {
          setActiveId(topEntry.target.id);
        }
      },
      {
        // Trigger when heading enters top 20% of viewport
        rootMargin: '-80px 0px -80% 0px',
        threshold: 0,
      },
    );

    for (const heading of headings) {
      const element = document.getElementById(heading.id);
      if (element) observer.observe(element);
    }

    return () => observer.disconnect();
  }, [headings]);

  // Don't render TOC if fewer than 2 headings
  if (headings.length < 2) return null;

  return (
    <nav className={cn('hidden xl:block', className)} aria-label='Table of contents'>
      <div className='sticky top-24'>
        <div className='mb-3 flex items-center gap-2 font-semibold text-foreground'>
          <List className={ICON_SIZES.SIZE_4} aria-hidden='true' />
          <span className={TYPOGRAPHY.TEXT_SM}>On this page</span>
        </div>
        <ul className='space-y-2 border-foreground/10 border-l'>
          {headings.map((heading) => {
            const isActive = activeId === heading.id;
            return (
              <li key={`${heading.id}-${heading.index}`}>
                <a
                  href={`#${heading.id}`}
                  aria-current={isActive ? 'true' : undefined}
                  onClick={(e) => {
                    e.preventDefault();
                    const element = document.getElementById(heading.id);
                    if (element) {
                      // Update URL hash for deep linking / back button support
                      history.pushState(null, '', `#${heading.id}`);
                      // Make element focusable and focus it for a11y
                      element.setAttribute('tabindex', '-1');
                      element.focus({ preventScroll: true });
                      // Smooth scroll to element
                      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
                      setActiveId(heading.id);
                    }
                  }}
                  className={cn(
                    '-ml-px block border-l-2 py-1 pl-4 transition-colors',
                    TYPOGRAPHY.TEXT_SM,
                    isActive
                      ? 'border-primary font-medium text-primary'
                      : 'border-transparent text-muted-foreground hover:border-foreground/30 hover:text-foreground',
                  )}
                >
                  {heading.text}
                </a>
              </li>
            );
          })}
        </ul>
      </div>
    </nav>
  );
}
